Name:
Matrikelnummer:

___

In [2]:
# Imports
import pandas as pd

___
**_Bitte beachten:_**

- In Code-Zellen soll (bei Bedarf kommentierter) Code eingefügt werden. In Raw-Zellen erwarten wir Antworten im Freitext-Format.
- Fragestellungen sind teilweise bewusst etwas offener formuliert, weil Sie auch im Arbeitsleben nur selten mit ganz spezifischen Anweisungen rechnen können. Es gibt häufig mehrere mögliche Lösungen, dies wird in der Korrektur  berücksichtigt.

___

# (I can't get no) satisfaction
Wir werden in diesem Kurs mit einem Datensatz arbeiten, der verschiedene Informationen über Angestellte einer fiktiven Firma namens *Fiktiva* enthält. Mithilfe des Datensatzes soll die Fragestellung beantwortet werden, ob ein\*e Angestellte\*r in der Firma zufrieden ist (`satisfied = 1`) oder nicht (`satisfied = 0`). In dieser Kurseinheit werden wir uns mit den Daten vertraut machen und mit einigen Fragen zur Datenqualität auseinandersetzen. Wir gehen für die weiteren Analysen davon aus, dass diese Analyse, die Sie nun durchführen, Anfang März 2021 stattfindet (und somit kurz nach der Erhebung der Daten).

Manchmal werden zur Beantwortung von Fragen weitere Informationen benötigt. Sie können hierfür auch externe Quellen verwenden und bspw. die Datei `metadata.txt` zu Rate ziehen, aber auch alle Informationen aus dem Fiktiva-Newsletter.

## Daten laden
Den Datensatz (*employees_satisfaction.csv*) finden Sie im Moodle. Laden Sie ihn in ein Pandas-Dataframe, so dass die erste Spalte als Index (Row Label) verwendet wird. Geben Sie die ersten 10 Zeilen aus.

In [3]:
# Ihre Lösung
df = pd.read_csv("data/employees_satisfaction.csv", index_col=0)
df.head(10)

,emp_id,age,Dept,education,recruitment_type,job_level,rating,awards,certifications,salary,gender,entry_date,last_raise,satisfied
0,HR8270,28,HR,PG,Referral,5,2.0,1,0,86750,m,2019-02-01,NaN,1
1,TECH1860,50,Technology,PG,Recruitment Agency,3,5.0,2,1,42419,Male,2017-01-17,NaN,0
2,TECH6390,43,Technology,UG,Referral,4,1.0,2,0,65715,f,2012-08-27,NaN,1
3,SAL6191,44,Sales,PG,On-Campus,2,3.0,0,0,29805,f,2017-07-25,NaN,1
4,HR6734,33,HR,UG,Recruitment Agency,2,1.0,5,0,29805,m,2019-05-17,NaN,1
5,PUR7265,40,Purchasing,UG,Walk-in,3,3.0,7,1,42419,m,2004-04-22,0.02,1
6,PUR1466,26,Purchasing,UG,Referral,5,5.0,2,0,86750,m,2019-12-10,NaN,1
7,TECH5426,25,Technology,UG,Recruitment Agency,1,1.0,4,0,24076,Female,2017-03-18,NaN,0
8,HR6578,35,HR,PG,Referral,3,4.0,0,0,42419,f,2015-04-02,NaN,1
9,TECH9322,45,Technology,PG,Referral,3,3.0,9,0,42419,f,2004-03-19,0.07,0

## Erste Datenanalyse

Machen Sie sich mit den Daten vertraut:
- Wie viele Zeilen hat der Datensatz?
- Wie viele Spalten hat der Datensatz?
- Welche Spalten beinhaltet der Datensatz?
- Welchen Datentyp haben die einzelnen Spalten?
- Ermitteln Sie statistische Kennzeichen der numerischen Spalten.
- Gibt es fehlende Werte in den Daten und wenn ja, bei welchen Spalten?

In [6]:
# Ihre Lösung (nutzen Sie dafür untenstehende Zellen)

In [4]:
# Wie viele Zeilen hat der Datensatz? 
df.shape[0]

500

In [5]:
# Wie viele Spalten hat der Datensatz?
df.shape[1]

14

In [6]:
# Welche Spalten beinhaltet der Datensatz?
df.columns

Index(['emp_id', 'age', 'Dept', 'education', 'recruitment_type', 'job_level',
       'rating', 'awards', 'certifications', 'salary', 'gender', 'entry_date',
       'last_raise', 'satisfied'],
      dtype='object')

In [7]:
# Welchen Datentyp haben die einzelnen Spalten?
df.dtypes

emp_id               object
age                   int64
Dept                 object
education            object
recruitment_type     object
job_level             int64
rating              float64
awards                int64
certifications        int64
salary                int64
gender               object
entry_date           object
last_raise          float64
satisfied             int64
dtype: object

In [8]:
# Ermitteln Sie statistische Kennzeichen der numerischen Spalten.
df.describe()

,age,job_level,rating,awards,certifications,salary,last_raise,satisfied
count,500.000000,500.000000,471.000000,500.000000,500.000000,500.000000,26.000000,500.000000
mean,39.694000,3.032000,3.093418,4.570000,0.514000,50416.056000,0.049231,0.714000
std,8.477033,1.423738,1.423129,2.989812,0.628167,23671.392661,0.029519,0.452342
min,22.000000,1.000000,1.000000,0.000000,0.000000,24076.000000,0.010000,0.000000
25%,34.000000,2.000000,2.000000,2.000000,0.000000,29805.000000,0.020000,0.000000
50%,39.000000,3.000000,3.000000,5.000000,0.000000,42419.000000,0.050000,1.000000
75%,47.000000,4.000000,4.000000,7.000000,1.000000,65715.000000,0.077500,1.000000
max,56.000000,5.000000,5.000000,25.000000,9.000000,86750.000000,0.100000,1.000000

In [9]:
# Gibt es fehlende Werte in den Daten und wenn ja, bei welchen Spalten?
df.isna().sum()

emp_id                0
age                   0
Dept                  0
education             0
recruitment_type      0
job_level             0
rating               29
awards                0
certifications        0
salary                0
gender                3
entry_date            0
last_raise          474
satisfied             0
dtype: int64

## Datenqualität

<div class="alert alert-block alert-warning">
    
**Hinweis**: Bei den folgenden Fragen geht es um Ihre Einschätzung. Ziel ist es, sich mit dem Thema Datenqualität auseinanderzusetzen und sich mit Fragestellungen in Bezug auf Data Fitness, etc. zu beschäftigen.
    
</div>

Was denken Sie über den Datensatz? Ist dieser geeignet, um die Fragestellung über die Zufriedenheit der Angestellten zu beantworten? Reichen die angegebenen Informationen zur Beantwortung der Fragestellung aus? Wenn nicht, welche Informationen würden Sie noch verwenden? Begründen Sie Ihre Antworten.

Hinweis: Bei der Beurteilung geht es um die Daten selbst, nicht um deren Erhebung. Dazu folgt noch eine Fragestellung.

Ihre Einschätzung:

Für welche weiteren Fragestellungen/Analysen könnte der Datensatz geeignet sein? Zählen Sie mindestens drei sinnvolle Aspekte auf.

Ihre Einschätzung:

Stellen Sie Überlegungen zur Datenerhebung an. Welche Faktoren könnten die Datenqualität beeinträchtigen? 
Nennen Sie mindestens zwei Einschränkungen und begründen Sie Ihre Antworten.

Ihre Einschätzung:

Beurteilen Sie den Datensatz bzgl. der Aspekte zur Datenqualität, die Sie im Kurstext in Kapitel 3 unter "Assessing Data Integrity" kennengelernt haben. Begründen Sie Ihre Antworten.

In [ ]:
# In dieser Zelle haben Sie Platz für Analysen bzgl. der Datenqualität
# Bewertet werden aber nur Ihre Antworten in der untenstehenden Raw-Zelle, gekennzeichnet mit "Ihre Einschätzung"!

Ihre Einschätzung:

Stellen Sie sich vor, dieser Datensatz soll dazu verwendet werden, um die Zufriedenheit von Angestellten vorherzusagen und daraus wiederum Rückschlüsse auf das Kündigungswahrscheinlichkeiten zu schließen. Für wie zuverlässig würden Sie entsprechende Wahrscheinlichkeiten halten? Begründen Sie Ihre Antwort.

Ihre Einschätzung:

Nehmen Sie an, mithilfe des Datensatzes wäre ein zuverlässiges Modell mit guten Vorhersagewahrscheinlichkeiten trainiert worden, um die Zufriedenheit der Angestellten zu bestimmen. Nun möchte eine andere Firma aus der gleichen Branche dasselbe Modell für ihre Angestellten nutzen. Denken Sie, das Modell würde auch für die andere Firma zuverlässige Vorhersagen treffen? Begründen Sie Ihre Antwort.

Ihre Einschätzung:

Überlegen Sie, welche Vorverarbeitungsschritte für den Datensatz notwendig wären. Nennen Sie mindestens drei sinnvolle Vorverarbeitungsschritte.

Ihre Einschätzung: