# Codealong Notebook

Use this notebook as your "scratch pad" as you go through the course contents. Feel free to copy any example code and tweak it to get a better understanding of how it works!

Use the **+** button or `Insert` menu to add additional code cells as needed.

## Step 1

### Loading the Data with `pandas`

In [3]:
import requests

# Get the Wikipedia page for "2022" since OpenAI's models stop in 2021
params = {
    "action": "query", 
    "prop": "extracts",
    "exlimit": 1,
    "titles": "2022",
    "explaintext": 1,
    "formatversion": 2,
    "format": "json"
}
resp = requests.get("https://en.wikipedia.org/w/api.php", params=params)
response_dict = resp.json()
response_dict["query"]["pages"][0]["extract"].split("\n")

['2022 (MMXXII) was a common year starting on Saturday of the Gregorian calendar, the 2022nd year of the Common Era (CE) and Anno Domini (AD) designations, the 22nd  year of the 3rd millennium and the 21st century, and the  3rd   year of the 2020s decade.  ',
 'The year saw the removal of nearly all COVID-19 restrictions and the reopening of international borders in most countries, while the global rollout of COVID-19 vaccines continued. The global economic recovery from the pandemic continued, though many countries experienced an ongoing inflation surge; in response, many central banks raised their interest rates to landmark levels. The world population reached eight billion people in 2022. The year also witnessed numerous natural disasters, including two devastating Atlantic hurricanes (Fiona and Ian), and the most powerful volcano eruption of the century so far. The later part of the year also saw the first public release of ChatGPT by OpenAI starting an arms race in artificial intelligence which increased in intensity into 2023, as well as the collapse of the cryptocurrency exchange FTX.',
 '2022 was also dominated by wars and armed conflicts. While escalations into the internal conflict in Myanmar and the Tigray War dominated the heightening of tensions within their regions and each caused over 10,000 deaths, 2022 was most notable for the Russian invasion of Ukraine, the largest armed conflict in Europe since World War II. The invasion caused the displacement of 15.7 million Ukrainians (8 million internally displaced persons and 7.7 million refugees), and led to international condemnations and sanctions and nuclear threats, the withdrawal of hundreds of companies from Russia, and the exclusion of Russia from major sporting events.',
 '',
 '',
 '== Events ==',
 '',
 '',
 '=== January ===',
 ' January 1 – The Regional Comprehensive Economic Partnership, the largest free trade area in the world, comes into effect for Australia, Brunei, Cambodia, China, Indonesia, Japan, South Korea, Laos, Malaysia, Myanmar, New Zealand, the Philippines, Singapore, Thailand, and Vietnam.',
 'January 2 – Abdalla Hamdok resigns as Prime Minister of Sudan amid deadly protests.',
 'January 4 – The five permanent members of the UN Security Council—China, France, Russia, the United Kingdom and the United States—issue a rare joint statement affirming that "a nuclear war cannot be won and must never be fought."',
 'January 5 – A nationwide state of emergency is declared in Kazakhstan in response to the 2022 Kazakh unrest. The cabinet of prime minister Askar Mamin resigns, while president Kassym-Jomart Tokayev removes former president Nursultan Nazarbayev, widely regarded as being the real power in the country, from his position as Chairman of the Security Council of Kazakhstan.',
 'January 6 – The CSTO deploys a "peacekeeping" mission in Kazakhstan, including Russian paratroopers, following a request by Kazakh president Tokayev.',
 'January 7 – COVID-19 pandemic: The number of COVID-19 cases exceeds 300 million worldwide.',
 'January 9 – February 6 – The 2021 Africa Cup of Nations is held in Cameroon, with Senegal winning their first championship.',
 'January 10 – The first successful heart transplant from a pig to a human patient occurs in Baltimore, Maryland, United States.',
 "January 15 – A large eruption of Hunga Tonga–Hunga Ha'apai, a submarine volcano in Tonga, triggers tsunami warnings in Australia, Canada, Chile, Fiji, Japan, New Zealand, Samoa, and the United States.",
 'January 16 – World No. 1 tennis champion Novak Djokovic is deported from Australia following a high-profile legal case regarding his COVID-19 vaccination status, preventing his participation in the 2022 Australian Open.',
 'January 23',
 'Tropical Storm Ana kills 115 people in Madagascar, Malawi and Mozambique, days after a series of floods killed 11 people in Madagascar.',
 "A coup d'état in Burkina Faso removes president Roch Kaboré from power. The Burkinabé military cites the government's failure to contain activities of Islamist militants within the country as a reason for the coup.",
 'January 24 – The federal government under Scott Morrison announces that, after more than three years of confidential negotiations, copyright ownership of the Australian Aboriginal Flag has been transferred to the Commonwealth.',
 'January 28 – COVID-19 pandemic: The number of vaccinations administered worldwide exceeds 10 billion.',
 '',
 '',
 '=== February ===',
 'February 3 – Islamic State leader Abu Ibrahim al-Hashimi al-Qurashi is killed in Atme during a counter-terrorism raid by U.S. special forces in north-western Syria.',
 'February 4 – China and Russia issue a joint statement opposing further NATO expansion, expressing "serious concerns" about the AUKUS security pact, and pledging to cooperate with each other on a range of issues.',
 'February 4 – February 20 – The 2022 Winter Olympics are held in Beijing, China, making it the first city ever to host both the Summer Olympics and Winter Olympics.',
 'February 5 – Cyclone Batsirai kills a total of 123 people across Madagascar, Mauritius, and Réunion two weeks after Tropical Storm Ana killed 115 people in the same region.',
 'February 6 – Queen Elizabeth II celebrates her "Platinum Jubilee", marking 70 years as Queen of the United Kingdom.',
 'February 9 – The biggest breakthrough in fusion energy since 1997 is reported at the Joint European Torus in Oxford, the UK, with 59 megajoules produced over five seconds (11 megawatts of power), more than double the previous record.',
 "February 21 – February 24 – Russian President Vladimir Putin signs a decree declaring the Luhansk People's Republic and Donetsk People's Republic as independent from Ukraine, and, despite international condemnation and sanctions, begins a full-scale invasion of Ukraine; at dawn on 24 February missiles strike Kyiv. Ukraine severs diplomatic relations with Russia, followed by the Federated States of Micronesia on 25 February.",
 'February 26 – Russian invasion of Ukraine: The EU, US, and their allies commit to removing Russian banks from the SWIFT payment system, as well as imposing measures on the Russian Central Bank and further restrictions on Russian elites. These and other sanctions fuel a financial crisis in Russia.',
 'February 27',
 'Russian invasion of Ukraine: Putin orders Russia\'s nuclear deterrent forces to be on "special alert", their highest level, in response to what he calls "aggressive statements" by NATO. The move is condemned by the US.',
 'Russian invasion of Ukraine: European nations ban Russian flights in their airspace.',
 'In a constitutional referendum, Belarus votes to revoke its non-nuclear status and to allow the country to host Russian forces permanently.',
 'February 28',
 'The Intergovernmental Panel on Climate Change (IPCC) releases the second part of its Sixth Assessment Report on climate change. It concludes that many impacts are on the verge of becoming "irreversible".',
 'Russian invasion of Ukraine: Russian and Ukrainian officials meet on the Belarus-Ukraine border for the first round of peace talks, with no resolution.',
 'Russian invasion of Ukraine: Football governing bodies FIFA and UEFA suspend Russian clubs and national teams from all competitions.',
 '2022 Russian financial crisis: In an unprecedented move, Switzerland, Monaco, Singapore and South Korea impose unilateral sanctions over Russia including the introduction of export controls and asset freezes.',
 '',
 '',
 '=== March ===',
 'March 1',
 'Russian invasion of Ukraine: World Athletics bans both Russia and Belarus from competing in all of its events.',
 "Russian invasion of Ukraine: In an emergency session, United Nations member states pass a resolution deploring Russia's invasion of Ukraine and calling for the immediate withdrawal of its forces.",
 'March 2',
 'Russian invasion of Ukraine: Russia captures its first large city, the Black Sea port of Kherson, as shelling intensifies across many parts of Ukraine, including civilian areas.',
 'Russian invasion of Ukraine: The United Nations reports that over a million refugees have now fled from Ukraine to other countries.',
 'The International Criminal Court begins an investigation into possible war crimes committed by Russia in Ukraine.',
 'March 3',
 'Russian invasion of Ukraine: Russia is condemned by world leaders following an attack by its troops on the Zaporizhzhia nuclear plant – the largest in Europe – which led to a fire at the site.',
 'The National Assembly of Armenia elects incumbent minister of High-Tech Industry and former mayor of Yerevan, Vahagn Khachaturyan, as president of Armenia following the resignation of Armen Sarkissian.',
 'March 4 – March 13 – The 2022 Winter Paralympics are held in Beijing, China, making it the first city to host both Summer Paralympics and Winter Paralympics.',
 'March 4 – Insurgency in Khyber Pakhtunkhwa: An Afghan man on behalf of the Islamic State – Khorasan Province commits a suicide attack at a Shia mosque in Peshawar, Khyber Pakhtunkhwa, Pakistan, killing 63 people.',
 "March 5 – Researchers in the Antarctic find Endurance, one of the greatest ever undiscovered shipwrecks, which sank in 1915 during Ernest Shackleton's exploration.",
 'March 7 – COVID-19 pandemic: The global death toll from COVID-19 surpasses 6 million.',
 'March 8 – The US and UK announce a ban on Russian oil, while the EU announces a two-thirds reduction in its demand for Russian gas.',
 'March 9',
 '2022 South Korean presidential election: People Power Party candidate Yoon Suk-yeol is narrowly elected President of South Korea.',
 "Russian invasion of Ukraine: Russia is condemned by world leaders following an air strike in Mariupol that destroys a hospital including a maternity and children's ward.",
 'March 10 – The National Assembly of Hungary elects former minister for Family Affairs, Katalin Novák, as president of Hungary in a 137–51 vote.',
 "March 11 – Gabriel Boric is sworn in as President of Chile. He becomes the youngest head of state in the nation's history and the first to be born during the military dictatorship of Augusto Pinochet.",
 'March 12 – 2022 Turkmenistan presidential election: Serdar Berdimuhamedow, son of former President Gurbanguly Berdimuhamedow, wins with 89% of the total votes.',
 'March 16 – Russian invasion of Ukraine: A Russian airstrike on the Mariupol Theatre in Mariupol kills an estimated 600 civilians sheltering inside.',
 'March 19 – The apostolic constitution Praedicate evangelium, reforming the Roman Curia, is promulgated by Pope Francis, coming into force on 5 June.',
 'March 21 – China Eastern Airlines Flight 5735 crashes in Guangxi, China, killing all 133 people on board.',
 'March 24 – Russian invasion of Ukraine: NATO announces that four new battlegroups totaling 40,000 troops will be deployed in Bulgaria, Hungary, Romania and Slovakia, along with enhanced readiness for potential chemical, biological, radiological and nuclear threats.',
 'March 27 – The M23 offensive begins in North Kivu, Democratic Republic of the Congo.',
 'March 29 – The Democratic Republic of the Congo is admitted to the East African Community.',
 'March 31 – Expo 2020 closes in Dubai after a 6-month run; originally scheduled for 10 April 2021, it was delayed due to the COVID-19 pandemic.',
 '',
 '',
 '=== April ===',
 'April 3',
 "Russian invasion of Ukraine: As Russia's forces retreat from areas near Kyiv, it is accused by Ukraine of war crimes, amid mounting evidence of indiscriminate civilian killings, including the Bucha massacre.",
 'The second round of voting of the 2022 Costa Rican general election is held, and Social Democratic Progress Party presidential candidate Rodrigo Chaves Robles is elected president.',
 'April 4 – The Intergovernmental Panel on Climate Change (IPCC) releases the third and final part of its Sixth Assessment Report on climate change, warning that greenhouse gas emissions must peak by 2025 at the latest and decline 43% by 2030, in order to limit global warming to 1.5 °C (2.7 °F).',
 'April 6 – The first known dinosaur fossil linked to the very day of the Chicxulub impact is reported by palaeontologists.',
 'April 7',
 'The UN votes by 93–24 to suspend Russia from the Human Rights Council, with 58 countries abstaining.',
 "President of Yemen Abdrabbuh Mansur Hadi resigns from office, dismisses vice president Ali Mohsen al-Ahmar, and transfers both offices' powers to the newly formed eight-member Presidential Leadership Council, chaired by Rashad al-Alimi.",
 'April 8',
 'Russian invasion of Ukraine: Russia is condemned by world leaders following a missile attack on Kramatorsk train station, which kills 59 civilians trying to evacuate, including seven children.',
 "Global food prices increase to their highest level since the UN's Food Price Index began in 1990, with commodities such as wheat rising by nearly 20% as a result of the Ukraine crisis.",
 'April 11 – The National Assembly of Pakistan elects leader of the opposition Shehbaz Sharif as prime minister of Pakistan, after Imran Khan is removed from office following a motion of no confidence two days prior.',
 'April 13 – COVID-19 pandemic: The number of confirmed cases exceeds 500 million worldwide.',
 'April 14 – Russian invasion of Ukraine: The Russian flagship Moskva becomes the largest warship to be sunk in action since World War II. Ukraine claims to have struck it with Neptune anti-ship missiles, while Russia claims it sank during stormy weather after an onboard fire.',
 'April 18 – Russian invasion of Ukraine: The battle of Donbas begins, leading to the deaths of several thousand military personnel and civilians.',
 'April 19 – The second round of voting of the 2022 East Timorese presidential election is held and the National Congress for Timorese Reconstruction party presidential candidate, former president and former prime minister José Ramos-Horta is elected.',
 'April 20 – A European Southern Observatory team announce the discovery of micronovae, a new type of exploding star.',
 'April 22 – The Large Hadron Collider recommences full operations, three years after being shut down for upgrades.',
 'April 24 – The 2022 Slovenian parliamentary election is held to elect all 90 members of the National Assembly of Slovenia, the lower house of the Slovenian Parliament; the Freedom Movement party becomes the largest party, winning 41 of 90 seats.',
 'April 25 – Elon Musk reaches an agreement to acquire the social media network Twitter (which he later rebrands as X) for $44 billion USD, which later closes in October.',
 'April 27 – The European Union accuses Russia of blackmail after gas supplies to Poland and Bulgaria are halted by energy giant Gazprom.',
 'April 28 – The Parliament of Montenegro elects a new government with Dritan Abazović as prime minister, following a motion of no confidence against the government of Zdravko Krivokapić.',
 '',
 '',
 '=== May ===',
 'May 6 – 2022 monkeypox outbreak: An outbreak of monkeypox begins when the first monkeypox virus case is reported in London, the United Kingdom.',
 'May 9',
 'Prime Minister of Sri Lanka Mahinda Rajapaksa resigns as a result of massive protests against his government across the country. He is succeeded by Ranil Wickremesinghe as prime minister three days later.',
 '2022 Philippine presidential election: Bongbong Marcos and Sara Duterte are elected the 17th President and 15th Vice President of the Philippines in a landslide victory.',
 'May 10–May 14 – The Eurovision Song Contest 2022 is held in Turin, Italy. The contest is won by Ukrainian folk-rap group Kalush Orchestra with their song "Stefania".',
 'May 12 – The Event Horizon Telescope collaboration reveals its first image of Sagittarius A*, the supermassive black hole at the centre of the Milky Way.',
 'May 13 – Mohamed bin Zayed Al Nahyan is elected as the 3rd president of the United Arab Emirates by the Federal Supreme Council following the death of Khalifa bin Zayed Al Nahyan a day earlier.',
 'May 15 – Former President of Somalia Hassan Sheikh Mohamud is elected president again, beating President Mohamed Abdullahi Mohamed.',
 'May 16 – Russian invasion of Ukraine: The Siege of Mariupol ends in a Russian victory as Ukrainian troops are evacuated from Mariupol.',
 'May 20 – 2022 monkeypox outbreak: The World Health Organization (WHO) holds an emergency meeting to discuss the spread of monkeypox in nearly a dozen countries, as the number of reported cases reaches 100.',
 'May 21 – 2022 Australian federal election: The Labor party, led by Anthony Albanese, defeats the Liberal-National Coalition government led by Prime Minister Scott Morrison. Albanese would be sworn in on May 23.',
 'May 24 – Uvalde school shooting: 18-year-old Salvador Ramos fatally shoots 19 students and two teachers at Robb Elementary School.',
 'May 27 – Fiji announces that it will become the 14th member of the Indo-Pacific Economic Framework for Prosperity in order to counter Chinese influence in the Pacific. This comes amid a visit by Chinese foreign minister Wang Yi to Kiribati.',
 'May 28 – Spanish club Real Madrid beat English club Liverpool 1–0 to win the UEFA Champions League final played at the Stade de France in Paris, France.',
 '',
 '',
 '=== June ===',
 'June 4 – Retired general Bajram Begaj is elected the 9th President of Albania by the parliament in the 4th round of voting.',
 'June 5 – At least 50 people are killed in a dual mass shooting-bomb attack in Owo, Nigeria.',
 'June 14 – Canada and Denmark end their competing claims for Hans Island by dividing the island roughly in half, ending what was referred to as the Whisky War.',
 'June 19',
 "The second round of the 2022 legislative election is held in France, resulting in a hung parliament, with President Macron's coalition losing its majority in the National Assembly. A newly-formed coalition of left-wing parties, led by far-left Jean-Luc Mélenchon, makes significant gains. Marine Le Pen's far-right National Rally also makes historic gains, increasing its number of MPs tenfold and becoming the largest opposition party in Parliament. Two weeks later, Macron's government is reshuffled, continuing as a minority administration.",
 'The second round of the 2022 Colombian presidential election is held, and former guerrilla fighter for the 19th of April Movement and incumbent senator, Gustavo Petro, defeats businessman and former mayor of Bucaramanga, Rodolfo Hernández Suárez.',
 'June 22 – A 6.2 earthquake strikes the Durand Line between Afghanistan and Pakistan, killing at least 1,163 people.',
 "June 23 – Dickon Mitchell's party wins a majority of seats in Grenada's general election, defeating Prime Minister Keith Mitchell's party. Mitchell is appointed Prime Minister of Grenada, following Keith Mitchell's resignation on June 24.",
 'June 26 – G7 leaders gather for a summit in Germany to discuss the situation in Ukraine. A ban on imports of Russian gold is announced.',
 'June 27 – 53 migrants from Mexico, Honduras, Guatemala, and El Salvador are found dead in a tractor trailer in San Antonio, Texas, United States.',
 'June 28 – June 30 – A NATO summit is held in Madrid, Spain along with the presence of guest countries from the European Union and the Indo-Pacific primarily searching for a consensual defensive reinforcement after the Russian invasion of Ukraine and the sustained threatening over the territorial integrity of other countries.',
 '',
 '',
 '=== July ===',
 'July 1 – Yair Lapid succeeds Naftali Bennett as Prime Minister of Israel, while Bennett succeeds Lapid as Alternate Prime Minister of Israel; this arrangement had been created after the 2021 Israeli legislative election, in which no party won an outright majority.',
 "July 6 – July 31 – UEFA Women's Euro 2022 is held in England, with the hosts winning their first major tournament since 1966.",

In [4]:
import pandas as pd

# Load page text into a dataframe
df = pd.DataFrame()
df["text"] = response_dict["query"]["pages"][0]["extract"].split("\n")
df

                                                  text
0    2022 (MMXXII) was a common year starting on Sa...
1    The year saw the removal of nearly all COVID-1...
2    2022 was also dominated by wars and armed conf...
3
4
..                                                 ...
254
255                                 == Nobel Prizes ==
256
257
258                                   == References ==

[259 rows x 1 columns]

In [5]:
from dateutil.parser import parse

# Clean up text to remove empty lines and headings
df = df[(df["text"].str.len() > 0) & (~df["text"].str.startswith("=="))]

# In some cases dates are used as headings instead of being part of the
# text sample; adjust so dated text samples start with dates
prefix = ""
for (i, row) in df.iterrows():
    # If the row already has " - ", it already has the needed date prefix
    if " – " not in row["text"]:
        try:
            # If the row's text is a date, set it as the new prefix
            parse(row["text"])
            prefix = row["text"]
        except:
            # If the row's text isn't a date, add the prefix
            row["text"] = prefix + " – " + row["text"]
df = df[df["text"].str.contains(" – ")].reset_index(drop=True)
df

                                                  text
0     – 2022 (MMXXII) was a common year starting on...
1     – The year saw the removal of nearly all COVI...
2     – 2022 was also dominated by wars and armed c...
3     January 1 – The Regional Comprehensive Econom...
4    January 2 – Abdalla Hamdok resigns as Prime Mi...
..                                                 ...
180  December 21–December 26 – A major winter storm...
181  December 24 – 2022 Fijian general election: Th...
182  December 29 – Brazilian football legend Pelé d...
183  December 31 – Former Pope Benedict XVI dies at...
184  December 7 – The world population was estimate...

[185 rows x 1 columns]

### Creating an Embeddings Index with `openai.Embedding`

In [6]:
import os
import openai

openai.api_key = os.getenv("OPENAI_API_KEY")

In [7]:
EMBEDDING_MODEL_NAME = "text-embedding-ada-002"
batch_size = 100
embeddings = []
for i in range(0, len(df), batch_size):
    # Send text data to OpenAI model to get embeddings
    response = openai.Embedding.create(
        input=df.iloc[i:i+batch_size]["text"].tolist(),
        engine=EMBEDDING_MODEL_NAME
    )

    # Add embeddings to list
    embeddings.extend([data["embedding"] for data in response["data"]])

# Add embeddings list to dataframe
df["embeddings"] = embeddings
df

,text,embeddings
0,– 2022 (MMXXII) was a common year starting on...,"[9.040244185598567e-05, -0.017994549125432968,..."
1,– The year saw the removal of nearly all COVI...,"[-0.010697541758418083, -0.023004746064543724,..."
2,– 2022 was also dominated by wars and armed c...,"[-0.009615330025553703, -0.015318214893341064,..."
3,January 1 – The Regional Comprehensive Econom...,"[-0.0005404727999120951, -0.024158069863915443..."
4,January 2 – Abdalla Hamdok resigns as Prime Mi...,"[-0.014883670955896378, 0.0011910186149179935,..."
...,...,...
180,December 21–December 26 – A major winter storm...,"[-0.024850230664014816, -0.023943288251757622,..."
181,December 24 – 2022 Fijian general election: Th...,"[-0.011599518358707428, -0.00938243605196476, ..."
182,December 29 – Brazilian football legend Pelé d...,"[-0.007591542787849903, 0.004114208742976189, ..."
183,December 31 – Former Pope Benedict XVI dies at...,"[0.023569442331790924, 0.007640643510967493, -..."
184,December 7 – The world population was estimate...,"[-0.0016404640628024936, -0.015250181779265404..."

In [8]:
df.to_csv("embeddings.csv")

## Step 2

### Finding Relevant Data with Cosine Similarity

In [9]:
import os
import openai

#openai.api_base = "https://openai.vocareum.com/v1"
openai.api_key = os.getenv("OPENAI_API_KEY")

In [10]:
import numpy as np
import pandas as pd

df = pd.read_csv("embeddings.csv", index_col=0)
df["embeddings"] = df["embeddings"].apply(eval).apply(np.array)
df

,text,embeddings
0,– 2022 (MMXXII) was a common year starting on...,"[9.040244185598567e-05, -0.017994549125432968,..."
1,– The year saw the removal of nearly all COVI...,"[-0.010697541758418083, -0.023004746064543724,..."
2,– 2022 was also dominated by wars and armed c...,"[-0.009615330025553703, -0.015318214893341064,..."
3,January 1 – The Regional Comprehensive Econom...,"[-0.0005404727999120951, -0.024158069863915443..."
4,January 2 – Abdalla Hamdok resigns as Prime Mi...,"[-0.014883670955896378, 0.0011910186149179935,..."
...,...,...
180,December 21–December 26 – A major winter storm...,"[-0.024850230664014816, -0.023943288251757622,..."
181,December 24 – 2022 Fijian general election: Th...,"[-0.011599518358707428, -0.00938243605196476, ..."
182,December 29 – Brazilian football legend Pelé d...,"[-0.007591542787849903, 0.004114208742976189, ..."
183,December 31 – Former Pope Benedict XVI dies at...,"[0.023569442331790924, 0.007640643510967493, -..."
184,December 7 – The world population was estimate...,"[-0.0016404640628024936, -0.015250181779265404..."

In [11]:
EMBEDDING_MODEL_NAME = "text-embedding-ada-002"
USER_QUESTION = """What were the estimated damages of the 2023 \
Turkey-Syria earthquake?"""

# Generate the embedding response
response = openai.Embedding.create(
    input=[USER_QUESTION],
    engine=EMBEDDING_MODEL_NAME
)

# Extract the embeddings from the response
question_embeddings = response["data"][0]["embedding"]

print(question_embeddings[:100])

[0.00553178321570158, -0.024947911500930786, 0.002177121117711067, -0.012254414148628712, -0.02144855074584484, 0.002601235406473279, -0.03387593477964401, -0.013079358264803886, 0.0024498847778886557, -0.014982052147388458, 0.0162061620503664, 0.044413935393095016, -0.010231969878077507, -0.013179149478673935, 0.01508849672973156, -0.005395401734858751, 0.012400775216519833, -0.013039441779255867, 0.008202873170375824, -0.005724714137613773, -0.007444456685334444, 0.011476038955152035, 0.012387469410896301, -0.009120956063270569, 0.015194941312074661, 0.03209299221634865, 0.008049859665334225, -0.0023667251225560904, -0.0008465657592751086, -0.012141316197812557, 0.005505172535777092, -0.006552984472364187, -0.023524217307567596, 0.015261468477547169, -0.03246554732322693, -0.0075309425592422485, 0.006865664850920439, -0.004883137531578541, 0.023231495171785355, -0.0078436229377985, 0.010112219490110874, 0.028553714975714684, 0.012959607876837254, -0.007697261869907379, -0.017576634883880615, -0.004211207386106253, 0.017270607873797417, 0.0030968673527240753, -0.004816609900444746, 0.021182440221309662, 0.013072704896330833, 0.02673085406422615, -0.037867601960897446, -0.02022443898022175, -0.015634024515748024, -0.01651219092309475, -0.001379619468934834, -0.019665606319904327, -0.00027026902534998953, -0.011462733149528503, 0.009180830791592598, -0.00680579012259841, -0.028686771169304848, 0.0013729666825383902, -0.01389099657535553, -0.01531469076871872, 0.0076773036271333694, -0.021049384027719498, -0.019625689834356308, 0.010883942246437073, 0.050108712166547775, 0.047713711857795715, 0.000932220253162086, -0.05716065317392349, 0.035179879516363144, -0.004919727798551321, 0.017962496727705002, -0.006526373326778412, -0.007377929054200649, 0.0024498847778886557, 0.03651043772697449, -0.020171217620372772, -0.003675658954307437, 0.0014145465102046728, 0.0315873809158802, -0.0009114303393289447, 0.00519581837579608, 0.009420331567525864, -0.02916577085852623, 0.017869357019662857, 0.012866469100117683, 0.030336659401655197, -0.0034760755952447653, 0.009852761402726173, 0.0008478131494484842, -0.007597470656037331, -0.025706326588988304, 0.017017802223563194, -0.015673941001296043, -0.045877546072006226]

In [12]:
from openai.embeddings_utils import distances_from_embeddings

# Create a list containing the distances from question_embeddings
distances = distances_from_embeddings(
    question_embeddings,
    df["embeddings"],
    distance_metric="cosine"
)

print(distances[:100])

[0.2824168564616253, 0.2454698524500013, 0.217292355804789, 0.2724040373350154, 0.2655723973046469, 0.27733637386525967, 0.2445255873776606, 0.2615334626832, 0.2536834208890082, 0.2951562893280997, 0.3073406710962445, 0.2304318030641459, 0.2997100941592409, 0.2328279341200662, 0.27088533985704955, 0.3056408004590401, 0.26163075001818903, 0.2485099558489976, 0.26747340233187256, 0.3016659987655075, 0.22633539429117622, 0.306719254828678, 0.25189938491376473, 0.267311748273781, 0.2497621652816029, 0.2613268033394516, 0.2704718474943849, 0.26808112689563834, 0.24446174432773493, 0.2668961540089487, 0.27541650072494184, 0.24543230846283404, 0.2803507677456979, 0.27184282236072255, 0.2587530073678649, 0.23475380491838127, 0.26166318069490235, 0.2510088564656421, 0.2670030888799504, 0.28580654682131756, 0.23194116973460233, 0.27297992778327274, 0.2417437023469442, 0.2476178525744106, 0.27393073416254876, 0.25284762936582306, 0.27073072360160444, 0.3009327863180373, 0.22883305185088065, 0.2352865498256861, 0.3005291130958032, 0.254161233728073, 0.24920204187785744, 0.2634245812619046, 0.2903919675501868, 0.2737351591796563, 0.25143405962328125, 0.27590325091653667, 0.2583748490562803, 0.24589413533063442, 0.26777153819236044, 0.28165491800881814, 0.2482944553535369, 0.2529481575197351, 0.2908780573480966, 0.24715672410713962, 0.25706811787733663, 0.2521268639282571, 0.2607394231970439, 0.25560654885497835, 0.26195178606750535, 0.27971956620037486, 0.27660876863127215, 0.24878497257593535, 0.292258047109886, 0.2849052770285837, 0.30464334908478885, 0.27290427679614315, 0.24944312974481186, 0.25082051631254854, 0.28597423002016376, 0.2749635147762536, 0.27399773044064935, 0.2699376563735367, 0.2840400974292242, 0.27355736872102165, 0.28100374127075645, 0.2925229434544746, 0.27562054984994044, 0.24774166802477238, 0.27361198522625285, 0.2840720820985724, 0.2675389058202877, 0.1785170167837673, 0.30873793241634995, 0.2641361570676546, 0.2553886354924062, 0.2644675595624204, 0.30088426290388315, 0.27599250100849937]

In [13]:
df["distances"] = distances
df.sort_values(by="distances", ascending=True, inplace=True)
df.head(5)

,text,embeddings,distances
93,June 22 – A 6.2 earthquake strikes the Durand ...,"[-0.0017065758584067225, -0.002665197942405939...",0.178517
171,November 21 – A 5.6 earthquake strikes near Ci...,"[0.004124542232602835, -0.004101862199604511, ...",0.180608
109,July 27 – A 7.0 earthquake strikes the island ...,"[0.002066155895590782, 0.003913976717740297, 0...",0.189808
126,September 5 – A 6.8 earthquake strikes Luding ...,"[0.012683872133493423, 0.016343697905540466, 0...",0.201568
119,August 17 – Turkey and Israel agree to restore...,"[-0.010702475905418396, -0.014352227561175823,...",0.216978

In [14]:
df.to_csv("distances.csv")

## Step 3

### Tokenizing with `tiktoken`

In [24]:
import tiktoken
tokenizer = tiktoken.get_encoding("cl100k_base")
len(tokenizer.encode("Answer the question based on the context"))

7

### Composing a Custom Text Prompt

In [23]:
import tiktoken

MAX_TOKEN_COUNT = 200

# Create a tokenizer that is designed to align with our embeddings
tokenizer = tiktoken.get_encoding("cl100k_base")

# Count the number of tokens in the prompt template and question
prompt_template = """
Answer the question based on the context below, and if the question
can't be answered based on the context, say "I don't know"

Context: 

{}

---

Question: {}
Answer:"""

current_token_count = len(tokenizer.encode(prompt_template)) + \
                        len(tokenizer.encode(USER_QUESTION))

context = []
for text in df["text"].values:

    # Increase the counter based on the number of tokens in this row
    text_token_count = len(tokenizer.encode(text))
    current_token_count += text_token_count

    # Add the row of text to the list if we haven't exceeded the max
    if current_token_count <= MAX_TOKEN_COUNT:
        context.append(text)
    else:
        break

prompt = prompt_template.format("\n\n###\n\n".join(context), USER_QUESTION)
print(prompt)

Answer the question based on the context below, and if the question
can't be answered based on the context, say "I don't know"

Context:

June 22 – A 6.2 earthquake strikes the Durand Line between Afghanistan and Pakistan, killing at least 1,163 people.

###

November 21 – A 5.6 earthquake strikes near Cianjur in West Java, Indonesia, killing 635 people and injuring 7,700 more.

###

July 27 – A 7.0 earthquake strikes the island of Luzon in the Philippines killing 11 people and injuring over 600.

###

September 5 – A 6.8 earthquake strikes Luding County in Sichuan province, China, killing 117 and injuring 424.

###

August 17 – Turkey and Israel agree to restore full diplomatic relations after a period of tensions.

---

Question: What were the estimated damages of the 2023 Turkey-Syria earthquake?
Answer:

In [ ]:
import tiktoken

def create_prompt(question, df, max_token_count):
    """
    Given a question and a dataframe containing rows of text and their
    embeddings, return a text prompt to send to a Completion model
    """
    # Create a tokenizer that is designed to align with our embeddings
    tokenizer = tiktoken.get_encoding("cl100k_base")

    # Count the number of tokens in the prompt template and question
    prompt_template = """
Answer the question based on the context below, and if the question
can't be answered based on the context, say "I don't know"

Context: 

{}

---

Question: {}
Answer:"""

    current_token_count = len(tokenizer.encode(prompt_template)) + \
                            len(tokenizer.encode(question))

    context = []
    for text in get_rows_sorted_by_relevance(question, df)["text"].values:

        # Increase the counter based on the number of tokens in this row
        text_token_count = len(tokenizer.encode(text))
        current_token_count += text_token_count

        # Add the row of text to the list if we haven't exceeded the max
        if current_token_count <= max_token_count:
            context.append(text)
        else:
            break

    return prompt_template.format("\n\n###\n\n".join(context), question)

## Step 4

### Getting a Custom Q&A Response with `openai.Completion`

In [25]:
answer = openai.Completion.create(
    model="gpt-3.5-turbo-instruct",
    prompt=prompt,
    max_tokens=150
)["choices"][0]["text"].strip()
print(answer)

I don't know