# Step 2: Finding Relevant Data

Add your API key to the cell below then run it.

In [1]:
import os
import openai

#openai.api_base = "https://openai.vocareum.com/v1"
openai.api_key = os.getenv("OPENAI_API_KEY")

The code below loads in the embeddings you previously created. Run it as-is.

In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("embeddings.csv", index_col=0)
df["embeddings"] = df["embeddings"].apply(eval).apply(np.array)
df

,text,embeddings
0,– 2022 (MMXXII) was a common year starting on...,"[4.099189391126856e-05, -0.01798599772155285, ..."
1,– The year saw the removal of nearly all COVI...,"[-0.010677152313292027, -0.0230444073677063, -..."
2,– 2022 was also dominated by wars and armed c...,"[-0.009615330025553703, -0.015318214893341064,..."
3,January 1 – The Regional Comprehensive Econom...,"[-0.0005404727999120951, -0.024158069863915443..."
4,January 2 – Abdalla Hamdok resigns as Prime Mi...,"[-0.015138540416955948, 0.0011573187075555325,..."
...,...,...
180,December 21–December 26 – A major winter storm...,"[-0.024877460673451424, -0.023879770189523697,..."
181,December 24 – 2022 Fijian general election: Th...,"[-0.011654332280158997, -0.009327322244644165,..."
182,December 29 – Brazilian football legend Pelé d...,"[-0.007616951130330563, 0.004034563899040222, ..."
183,December 31 – Former Pope Benedict XVI dies at...,"[0.023569442331790924, 0.007640643510967493, -..."
184,December 7 – The world population was estimate...,"[-0.0016265329904854298, -0.015277454629540443..."

## TODO 1: Create Embeddings for the User's Question

In the previous exercise, you were given the code to create embeddings for everything in the dataset. Now your task is to create embeddings for just one string: the user's question. Assign the result to the variable `question_embeddings`. This variable should contain a list of 1,536 floating point numbers, and the provided code will print the first 100 once `question_embeddings` has been created correctly.

If you're getting stuck, you can click to reveal the solution then copy and paste this into the cell below.

---

<details>
    <summary style="cursor: pointer"><strong>Solution (click to show/hide)</strong></summary>

```python
EMBEDDING_MODEL_NAME = "text-embedding-ada-002"
USER_QUESTION = """What were the estimated damages of the 2023 \
Turkey-Syria earthquake?"""

# Generate the embedding response
response = openai.Embedding.create(
    input=USER_QUESTION,
    engine=EMBEDDING_MODEL_NAME
)

# Extract the embeddings from the response
question_embeddings = response["data"][0]["embedding"]

print(question_embeddings[:100])
```

</details>

In [3]:
EMBEDDING_MODEL_NAME = "text-embedding-ada-002"
USER_QUESTION = """What were the estimated damages of the 2023 \
Turkey-Syria earthquake?"""

# Generate the embedding response
response = openai.Embedding.create(
    input=[USER_QUESTION],
    engine=EMBEDDING_MODEL_NAME
)

# Extract the embeddings from the response
question_embeddings = response["data"][0]["embedding"]

print(question_embeddings[:100])

[0.00553178321570158, -0.024947911500930786, 0.002177121117711067, -0.012254414148628712, -0.02144855074584484, 0.002601235406473279, -0.03387593477964401, -0.013079358264803886, 0.0024498847778886557, -0.014982052147388458, 0.0162061620503664, 0.044413935393095016, -0.010231969878077507, -0.013179149478673935, 0.01508849672973156, -0.005395401734858751, 0.012400775216519833, -0.013039441779255867, 0.008202873170375824, -0.005724714137613773, -0.007444456685334444, 0.011476038955152035, 0.012387469410896301, -0.009120956063270569, 0.015194941312074661, 0.03209299221634865, 0.008049859665334225, -0.0023667251225560904, -0.0008465657592751086, -0.012141316197812557, 0.005505172535777092, -0.006552984472364187, -0.023524217307567596, 0.015261468477547169, -0.03246554732322693, -0.0075309425592422485, 0.006865664850920439, -0.004883137531578541, 0.023231495171785355, -0.0078436229377985, 0.010112219490110874, 0.028553714975714684, 0.012959607876837254, -0.007697261869907379, -0.017576634883880615, -0.004211207386106253, 0.017270607873797417, 0.0030968673527240753, -0.004816609900444746, 0.021182440221309662, 0.013072704896330833, 0.02673085406422615, -0.037867601960897446, -0.02022443898022175, -0.015634024515748024, -0.01651219092309475, -0.001379619468934834, -0.019665606319904327, -0.00027026902534998953, -0.011462733149528503, 0.009180830791592598, -0.00680579012259841, -0.028686771169304848, 0.0013729666825383902, -0.01389099657535553, -0.01531469076871872, 0.0076773036271333694, -0.021049384027719498, -0.019625689834356308, 0.010883942246437073, 0.050108712166547775, 0.047713711857795715, 0.000932220253162086, -0.05716065317392349, 0.035179879516363144, -0.004919727798551321, 0.017962496727705002, -0.006526373326778412, -0.007377929054200649, 0.0024498847778886557, 0.03651043772697449, -0.020171217620372772, -0.003675658954307437, 0.0014145465102046728, 0.0315873809158802, -0.0009114303393289447, 0.00519581837579608, 0.009420331567525864, -0.02916577085852623, 0.017869357019662857, 0.012866469100117683, 0.030336659401655197, -0.0034760755952447653, 0.009852761402726173, 0.0008478131494484842, -0.007597470656037331, -0.025706326588988304, 0.017017802223563194, -0.015673941001296043, -0.045877546072006226]

## TODO 2: Find Cosine Distances

Create a new list called `distances`, which represents the cosine distances between `question_embeddings` and each value in the `'embeddings'` column of `df`.

If you're getting stuck, you can click to reveal the solution then copy and paste this into the cell below.

---

<details>
    <summary style="cursor: pointer"><strong>Solution (click to show/hide)</strong></summary>

```python
from openai.embeddings_utils import distances_from_embeddings

# Create a list containing the distances from question_embeddings
distances = distances_from_embeddings(
    question_embeddings,
    df["embeddings"],
    distance_metric="cosine"
)

print(distances[:100])
```

</details>

In [4]:
from openai.embeddings_utils import distances_from_embeddings

# Create a list containing the distances from question_embeddings
distances = distances_from_embeddings(
    question_embeddings,
    df["embeddings"],
    distance_metric="cosine"
)

print(distances[:100])

[0.28234746764173135, 0.2455171097909099, 0.217292355804789, 0.2724040373350154, 0.26547525619540147, 0.27730425350462184, 0.24461928976454217, 0.2615334626832, 0.2537216358187827, 0.29511445897086563, 0.30736548516199036, 0.2303988532867446, 0.2997100941592409, 0.2328279341200662, 0.2709715812224258, 0.3056408004590401, 0.2614829193734647, 0.2485099558489976, 0.26747340233187256, 0.3016659987655075, 0.22633539429117622, 0.30680083323053053, 0.25189773733303444, 0.267311748273781, 0.2497621652816029, 0.2613268033394516, 0.2704718474943849, 0.26808112689563834, 0.24450335711792903, 0.2668961540089487, 0.2753232055815623, 0.24543873146877304, 0.2802376097360352, 0.27177401477463314, 0.2587530073678649, 0.23473488952219757, 0.2616299637495978, 0.25112026414877975, 0.2670030888799504, 0.28580654682131756, 0.23194116973460233, 0.27297992778327274, 0.24171910045870293, 0.2476178525744106, 0.2739733662719106, 0.25284762936582306, 0.27073072360160444, 0.30093262910448704, 0.2288247922326957, 0.2352865498256861, 0.3005291130958032, 0.2542067565900208, 0.24920204187785744, 0.26335609105144187, 0.29026562915829623, 0.2736830717028095, 0.25153616826861114, 0.27603521245946183, 0.2584145541406432, 0.24589413533063442, 0.2677583760000184, 0.28165491800881814, 0.2482944553535369, 0.2529481575197351, 0.2908780573480966, 0.24710744226637316, 0.25706811787733663, 0.2521373440275302, 0.260444117134941, 0.25564685386122177, 0.261946187619192, 0.2796028261212946, 0.27668404387681733, 0.24878497257593535, 0.2921548621253367, 0.2849052770285837, 0.30464334908478885, 0.27285848987993, 0.2494983739932971, 0.25082051631254854, 0.28597423002016376, 0.27480389395548577, 0.27399773044064935, 0.26992671493496934, 0.2840400974292242, 0.27355736872102165, 0.28100374127075645, 0.2925229434544746, 0.2753722171086245, 0.24781919088776938, 0.2736339088514984, 0.2840720820985724, 0.267567020797697, 0.17847794411559792, 0.3087190072225623, 0.2641754239877204, 0.2553886354924062, 0.2645058294729533, 0.30088426290388315, 0.27599250100849937]

## Sorting by Distance

The code below uses the `distances` list to update `df` then sorts `df` to find the most related rows. Shorter distance means more similarity, so we'll use an ascending sorting order. Run the cell below as-is.

In [5]:
df["distances"] = distances
df.sort_values(by="distances", ascending=True, inplace=True)
df.head(5)

,text,embeddings,distances
93,June 22 – A 6.2 earthquake strikes the Durand ...,"[-0.0015963754849508405, -0.002591762458905577...",0.178478
171,November 21 – A 5.6 earthquake strikes near Ci...,"[0.004122345708310604, -0.004109382163733244, ...",0.180616
109,July 27 – A 7.0 earthquake strikes the island ...,"[0.0020924704149365425, 0.0039183637127280235,...",0.189802
126,September 5 – A 6.8 earthquake strikes Luding ...,"[0.01265291590243578, 0.01628030464053154, 0.0...",0.201539
119,August 17 – Turkey and Israel agree to restore...,"[-0.01068311370909214, -0.014326412230730057, ...",0.216965

Great, now we have the dataset sorted from most relevant to least relevant! Let's save this as a CSV so we can load it in the next step and compose a custom prompt.

Run the cell below as-is.

In [6]:
df.to_csv("distances.csv")