Name:
Matrikelnummer:

> Das Geheimnis des Glücks liegt in der Freude am Genuss

___

In dieser Kurseinheit werden wir einige Techniken zur Datenvorverarbeitung und zum Data Cleaning anwenden.

**_Bitte beachten:_**

- In Raw-Zellen erwarten wir Antworten im Freitext-Format. In Code-Zellen soll Code eingefügt werden, bei Bedarf mit Kommentaren. Weitere Formate werden mit Markdown bearbeitet
- Fragestellungen sind teilweise bewusst etwas offener formuliert, weil Sie auch im Arbeitsleben nur selten mit ganz spezifischen Anweisungen rechnen können. Es gibt häufig mehrere mögliche Lösungen, dies wird in der Korrektur berücksichtigt.

Bei vielen Aufgaben empfiehlt es sich, reguläre Ausdrücke zu verwenden. Wenn Sie noch nicht mit Ihnen vertraut sind, können Sie das Tutorial auf dem <a href="https://regexone.com/">regexone</a> befolgen; um reguläre Ausdrücke online zu testen, können Sie <a href="https://regex101.com/">regex101</a> verwenden. Darüber hinaus gibt es im Internet viele weitere Alternativen.


___

Ziel ist es, die Zugänglichkeit von Lebensmitteln und Trinkwasser für die Bevölkerung in Deutschland zu analysieren.
Wir arbeiten weiter mit den Datensätzen Refill-Deutschland und Mundraub. Refill-Deutschland und Mundraub sind Plattformen, die die Standorte von Früchten, Pflanzen und Zapfstellen in Deutschland erfassen. Beide Datensätze stammen aus <a href="https://www.govdata.de/">GovData</a> und beinhalten geographische Punkte, an denen es freien Zugang zu Wasser und Lebensmittel gibt.

In den vorangegangenen Übungen wurden die Probleme und Informationslücken in den Datensätzen identifiziert, siehe Datenernte (Aufgabe 1.5), Refill-Deutschland und Mundraub’s Merkmale Analyze (Aufgabe 2.2 und Aufgabe 3.2), Refill-Deutschland und Mundraub’s WADi (Aufgabe 2.3 und Aufgabe 3.3), fesstellen.

Die Verwendung externer Quellen und das Einfügen von Anmerkungen am Ende des Protokolls ist weiterhin erlaubt! :)

In [1]:
# Imports
import pandas as pd
import numpy as np

Laden Sie den Datensatz von Refill-Deutschland in einen Dataframe mit dem Namen `df_refill` und verwenden Sie die dritte Spalte als Index. Bitte beachten Sie die Auswirkungen dieser Vorgehensweise. Geben Sie dann die ersten 5 Zeilen aus.
Der Datensatz ist in Moodle verfügbar (`refill.csv`).

In [2]:
# Datensatz laden
df_refill = pd.read_csv("KE2/refill.csv", index_col=2)
df_refill.head(5)

,FID,geom,title,description,addresslocality,streetaddress,postalcode,email,openinghours,license,telephone
id,,,,,,,,,,,
f6b479c4210c45c1b0282138ebde8f2f,MRN_Refill_4326_Point.1,POINT (8.465881798633319 49.48506140126151),Umgekrempelt,Faire Kleidung die nicht nur auf Labels sonder...,Mannheim,M2 15a,68161,info@umgekrempelt-mannheim.de,Di-Fr 11:00-14:00;15:00-19:00 Sa 12:00-18:00,CC0-1.0,0621 - 43674787
d24bcae66e96437fa8f998162196524e,MRN_Refill_4326_Point.2,POINT (8.68860304760216 49.41426788895124),Annas Unverpacktes,Unverpackte Biolebensmittel nachhaltiges und r...,Heidelberg,Ladenburger Straße 37,69120,annasunverpacktes@posteo.de,NaN,CC0-1.0,06221 6724604
d131c294325d4599ad0a7009ab35e140,MRN_Refill_4326_Point.3,POINT (8.703600032582694 49.37469998345463),Refill-Station im Stadtteilverein Boxberg e.V.,Der Stadtteilverein Boxberg e.V. geht mit der ...,Heidelberg,Boxbergring 12,69126,info@stadtteilverein-boxberg.de,Mo 17:00-18:30,CC0-1.0,06221 385314
e913384994cf41758097f97743b11b44,MRN_Refill_4326_Point.4,POINT (8.474144008231416 49.48366778413005),Wasserturm Mannheim,Öffnungszeiten: immer geöffnet,Mannheim,Friedrichsplatz,68161,NaN,NaN,CC0-1.0,NaN
2f7dfcf4261a4ae9a1e4c58d788dc7aa,MRN_Refill_4326_Point.5,POINT (8.376415375795409 49.38466715597765),Weltladen,Fairtrade Produkte,Schifferstadt,Lillengasse 8,67105,NaN,NaN,CC0-1.0,NaN

# Spalten transformieren
In den folgenden Aufgaben werden die Spalten des Datensatzes bearbeitet. Ziel ist es, die Spalten und deren Inhalte zu korrigieren oder anzupassen.

Bitte betrachten Sie den Inhalt der Spalten `title`, `addresslocality` und `streetaddress`, diese werden für die nächste Aufgabe benötigt.

## Taufzeit :: Rename column names
Die Spalte `title` bezieht sich auf den Namen der Einrichtung, `addresslocality` auf die Stadt und `streetaddress` kann abgekürzt werden. Benennen Sie die entsprechenden Spalten um.

In [3]:
# Ihre Lösung
proposedNames = {'title':'stationsname',
                 'addresslocality':'city',
                 'streetaddress':'address'}
df_refill.rename(columns = proposedNames, inplace = True)

Führen Sie die folgende Zelle aus. Überprüfen Sie die Formatierung des Inhalts der Spalte `telephone`.

In [4]:
df_refill.telephone.unique()

array(['0621 - 43674787', '06221 6724604', '06221 385314', nan,
       '0621 856506', '06221-3522920', '0621 22538', '(0621) 401484-5',
       '(0621) 4 10 05 0', '+49 621 26064', '(0 62 41) 8 53 - 35 07',
       '06323/9884080', '0174 5924673', '0621 293-8935', '06348/8210',
       '0621 / 21663', '06201 905610', '0049-6221-659687', '632696560',
       '0171 8327016', '0621/ 71419839', '07275/919491', '0621 1229693',
       '+49 621-181-1215', '06227-6531093', '6205396910', '06235-4930-0',
       '63224620', '06202 / 205-205', '0621-12510', '496215044277',
       '06201 - 8787805', '0621 8430389', '06221 23824', '06241-408158',
       '622101371600', '15154205538', '622472585', '06203-70211',
       '496235957032', '06235 3030', '0621 512 145', '+49 172 3675826',
       '1733214923', '06222 929315', '07274-2415', '06201/2598750',
       '06353-9893820', '4915785303987', '6221383890', '6221384427',
       '1718934455', '6204988392', '06252 305926', '06204 988 400',
       '496251854304', '06204/988450\xa0\xa0\xa0', '+49 6227 35-2601',
       '496227359640', '06227 6990', '+49 6227 398 2561',
       '0 62 27 8 29 70', '06227 398 44 66', '+49 621 484 954 29',
       '6222615850', '6234929433'], dtype=object)

## Gleich anrufen :: Datenformat
Wie Sie sehen können, haben die Zellen unterschiedliche Formate. Nehmen Sie die notwendigen Änderungen vor, damit die Telefonnummern die folgende Syntax haben:
<+49xxxxxxxxx>.

*Hinweis: Eine Möglichkeit, diese Aufgabe zu lösen, ist die Verwendung regulärer Ausdrücke.  Wenn Sie weitere Tipps benötigen, verwenden Sie den Schieberegler unten.*

Der erste reguläre Ausdruck, `regExp1` wird verwendet, um unerwünschte Zeichen wie Klammern oder Trennzeichen aus Telefonnummern zu entfernen. Die Ausdrücke `regExp2` und `regExp3` nutzen den Anker "^", um sicherzustellen, dass die Nummer mit "+49" beginnt.

Verwenden Sie die regulären Ausdrücke `regExp1`, `regExp2` und `regExp3`, um die jeweiligen Werte zu bereinigen und alle Telefonnummern in ein einheitliches Format zu überführen.

In [5]:
regExp1 = '[ /()-]'
regExp2 = '^(0049|0|49)'
regExp3 = '^6'

In [6]:
# Ihre Lösung
telWithFormat = df_refill[ df_refill.telephone.notna() ].telephone.str.strip()
df_refill.telephone = telWithFormat.replace(regExp1, '', regex=True)\
                              .replace(regExp2, '+49', regex=True)\
                              .replace(regExp3, '+496', regex=True)

&#x1F6A9; _Checkpoint 1_:Um die Änderungen zu überprüfen, führen Sie die folgende Zelle aus. Es wird eine Liste von Telefonnummern im erwarteten Format (<+49xxxxxxxxx>) als Ausgabe erwartet. Bitte beachten Sie, dass leere Werte vorhanden sind, aber keine ungültigen Werte vorkommen dürfen.

In [7]:
df_refill.telephone.unique()

array(['+4962143674787', '+4962216724604', '+496221385314', nan,
       '+49621856506', '+4962213522920', '+4962122538', '+496214014845',
       '+49621410050', '+4962126064', '+4962418533507', '+4963239884080',
       '+491745924673', '+496212938935', '+4963488210', '+4962121663',
       '+496201905610', '+496221659687', '+49632696560', '+491718327016',
       '+4962171419839', '+497275919491', '+496211229693',
       '+496211811215', '+4962276531093', '+496205396910', '+49623549300',
       '+4963224620', '+496202205205', '+4962112510', '+496215044277',
       '+4962018787805', '+496218430389', '+49622123824', '+496241408158',
       '+49622101371600', '15154205538', '+49622472585', '+49620370211',
       '+496235957032', '+4962353030', '+49621512145', '+491723675826',
       '1733214923', '+496222929315', '+4972742415', '+4962012598750',
       '+4963539893820', '+4915785303987', '+496221383890',
       '+496221384427', '1718934455', '+496204988392', '+496252305926',
       '+496204988400', '+496251854304', '+496204988450', '+496227352601',
       '+496227359640', '+4962276990', '+4962273982561', '+49622782970',
       '+4962273984466', '+4962148495429', '+496222615850',
       '+496234929433'], dtype=object)

# Fehlende Werte
Oft fehlen Werte in den Daten. Dies kann verschiedene Gründe haben, z.B. kann ein Wert absichtlich weggelassen werden (z.B. der Titel in einer Anrede) oder die Daten können nicht korrekt übertragen werden. Für viele Auswertungen ist es jedoch wichtig, dass es keine fehlenden Werte gibt.

Das Ersetzen fehlender Werte wird als (Missing Value) Imputation bezeichnet. Hierfür  gibt es verschiedene Strategien: 

- **_Wert ermitteln_**: Im besten Fall kann der korrekte Wert ermittelt werden, bspw. durch Rücksprache mit (Fach-)Expert*innen. Dies ist jedoch nur selten der Fall und häufig mit großem Aufwand verbunden. 
- **_Zeilen löschen_**: Wenn nur wenige Einzelwerte fehlen, kann es sinnvoll sein, die entsprechenden Zeilen zu löschen. Hierbei muss jedoch darauf geachtet werden, dass nicht zu viele Informationen verloren gehen. 
- **_Spalte löschen_**: Wenn in einer Spalte so viele Werte fehlen, dass sie diese keine Aussagekraft mehr hat, kann es sinnvoll sein, die gesamte Spalte zu entfernen. 
- **_Neuen Wert_**: Fehlen nur wenige Einzelwerte, so kann ein neuer Wert eingefügt werden.
- **_Neue Kategorie_**: Bei nominalen Werten kann eine neue Kategorie (z.B. ”Unbekannt”) hinzugefügt werden. 
- **_Mode Imputation_**: Fehlende Werte werden durch den am häufigsten Wert ersetzt. 
- **_Mean Imputation_**: Fehlende Werte werden durch den Mittelwert ersetzt. 
- **_Median Imputation_**: Fehlende Werte werden durch den Median ersetzt. 
Mode, Mean und Median Imputation können auch auf Basis der Werte einer anderen Spalte durchgeführt werden.
- **_Imputation mit_** 0 oder einem anderen **_konstanten Wert_**: Fehlende Werte werden durch eine Konstante ersetzt, z.B durch 0 oder eine andere Konstante, je nach Anwendung.
- **_Modellbasierte Imputation_**: Ein maschinelles Lernmodell wird darauf trainiert, die fehlenden Werte vorherzusagen. 

Zusätzlich zu den oben genannten Strategien ist es möglich, **_ein neues Feature_** zu erstellen, das anzeigt, ob eine Imputation durchgeführt wurde (=1) oder nicht (=0).


Im vorherigen Arbeitsblatt wurden die fehlenden Werte in den verschiedenen Spalten des Datensatzes notiert, siehe die Tabellen in KE2 Refill-Deutschland und Mundraub’s Merkmale Analyze (Aufgabe 2.2 und Aufgabe 3.2). Im Folgenden werden wir uns einige dieser Spalten genauer ansehen.
Ziel ist es, die fehlenden Werte mithilfe einer geeigneten Imputationsstrategie zu beheben.

## Email not found, bleiben Sie bitte in der Leitung
In der Spalte `email` fehlen 60,2% der Werte und in der Spalte `telephone` fehlen 63,5% der Werte. Entscheiden Sie sich für eine geeignete Imputation-Strategie und begründen Sie Ihre Wahl.

Ausgewählte Imputationsstrategie: Löschung der Spalten
Begründung: In beiden Spalten fehlt ein Großteil der Werte. Da die Informationen zu Email und Telefon zudem nicht relevant für unsere Fragestellung sind, werden die beiden Spalten gelöscht.

In [8]:
# Ihre Lösung
df_refill = df_refill.drop("email", axis=1)
df_refill = df_refill.drop("telephone", axis=1)

## Paket unzustellbar
Überprüfen Sie die Anzahl der fehlenden Werte in der `postalcode`-Spalte. Wählen Sie hier eine geeignete Imputationsstrategie und begründen Sie Ihre Wahl. Beachten Sie den Datentyp.

In [9]:
# Platz für Tests und Analysen
postIndices = df_refill[ df_refill.postalcode.isna() ].index
for i in postIndices:
    print(df_refill.loc[i, 'stationsname'], "::", df_refill.loc[i, 'city'])

Café am Rathaus :: Mannheim
Blumen Kronenberg :: Germersheim
Öffentlicher Trinkbrunnen / Paradeplatz  :: Mannheim

Ausgewählte Imputationsstrategie: Korrekten Wert ermitteln
Begründung: Die Postleitzahl kann abgeleitet werden, da zusätzliche Informationen verfügbar sind und es sich um wenige Werte handelt.

In [10]:
# Ihre Lösung
df_refill.loc[postIndices[0], 'postalcode'] = '68159' # Café am Rathaus, Mannheim
df_refill.loc[postIndices[1], 'postalcode'] = '76726' # Blumen Kronenberg, Germersheim
df_refill.loc[postIndices[2], 'postalcode'] = '68161' # Öffentlicher Trinkbrunnen / Paradeplatz, Mannheim

## Finde die Sackgasse
Wählen Sie eine geeignete Imputationsstrategie für die Spalte, die ursprünglich als `streetaddress` bezeichnet wurde. Begründen Sie Ihre Wahl.

In [11]:
# Platz für Tests und Analysen
addressIndices = df_refill[ df_refill.address.isnull() ].index
for i in addressIndices:
    print(df_refill.loc[i, 'stationsname'], "::", df_refill.loc[i, 'city'])

Café am Rathaus :: Mannheim
Öffentlicher Trinkbrunnen / Marktplatz :: Mannheim

Ausgewählte Imputationsstrategie: Korrekten Wert ermitteln und Neue Kategorie "Unbekannt"
Begründung: Die Adresse des Cafés kann aus zusätzlichen Informationen abgeleitet werden. Für den Brunnen kann die Adresse hingegen nicht ermittelt werden. Eine Möglichkeit wäre es, die entsprechende Zeile zu löschen. Wir entscheiden uns hier jedoch für die Alternative einer neuen Kategorie "Unbekannt", um möglichst wenig Informationen aus dem Datensatz zu verlieren.

In [12]:
# Ihre Lösung
df_refill.loc[addressIndices[0], 'address'] = "E3 15" # Café am Rathaus :: Mannheim
df_refill.loc[addressIndices[1], 'address'] = "Unbekannt" #Trinkbrunnen :: Mannheim

Schauen Sie sich die Spalte `description` genauer an. Führen Sie dazu die folgende Zelle aus:

In [13]:
df_refill.description.tail(5)

id
3857465138ca4751b5c3bf0f37c5a7a9    Öffnungszeiten Mo-Fr 10:00-19:00 Sa 10:00-16:0...
157f5fd9abeb4b0da08f479dc23eb7d2    Öffnungszeiten: Mo-Do 07:30-21:00 Fr;Sa 07:30-...
f51f03bf784348039424566b153e897a                    Öffnungszeiten: Mo-Sa 08:30-20:15
f0f71f729f6940caa48afcfbf7ae8e44                   Öffnungszeiten: Mo-Sa 9:30-20:00
83461e1e0e3145e89ab4e612829956c3    Caffee-Haus Kette die in der EU keine Steuern ...
Name: description, dtype: object

Die Öffnungszeiten sind teilweise in der Spalte `description` angegeben.

## Déjà vu :: Duplikate

Eine weitere Spalte, in der viele Werte fehlen, ist die Spalte `openinghours`. Im Gegensatz zu den vorhergehenden Spalten können die Werte aus der Spalte `description` entnommen werden.

*Hinweis: Diese Aufgabe kann aufgrund ihrer Komplexität in drei Niveaustufen bearbeitet werden (Anfängerniveau, Durchschnittsniveau, Expertenniveau).*

*_1. Anfängerniveau_: Auf diesem Niveau können Sie mithilfe von Pseudocode beschreiben, wie die Aufgabe gelöst werden könnte.*

*_2. Durchschnittsniveau_: Auf diesem Niveau kann man mit verschachtelten ifs und vielen Zeilen Code gelöst werden.*

*_3. Expertenniveau_: Auf dieser Niveau können Sie reguläre Ausdrücke verwenden. Wenn Sie diese Niveau auswählen, können Sie den Schieberegler unten verwenden, um den regulären Ausdruck anzuzeigen. Anschließend , können Sie die Codezelle vervollständigen, um die in dieser Aufgabe vorgesehenen Änderungen vorzunehmen.*

*Die Aufgabe muss nur mit einer Variante gelöst werden. Die zweite Variante (Durchschnittsniveau) ist dabei die umständlichste, weswegen wir aus Zeitgründen eher Variante 1 oder 3 empfehlen.*

In [14]:
# Regular expression to find “Öffnungszeiten” or derivatives (can be improved)
import re

# Keywords
OPENING_TAGS = re.compile(r'\b(Öffnungszeiten:?|Wir haben für Sie geöffnet):?\b', re.IGNORECASE)

# Keywords for Weekdays and 'FT' Feiertagen
DAYS = r'(?:Mo|Di|Mi|Do|Fr|Sa|So|FT)'

# Valid openinghours-blocks
# Days can be individual, in range separated by '-' and not consecutive separated by ';'.
OPENING_PATTERN = re.compile(rf'''
    (?:
    
        {DAYS}(?:-{DAYS})?(?:;{DAYS})* \s+           # Days         
    )?
    \d{{1,2}}[:.]\d{{2}}                             # Start time
    (?:-\d{{1,2}}[:.]\d{{2}})?                       # End time
    (?:;\d{{1,2}}[:.]\d{{2}}-\d{{1,2}}[:.]\d{{2}})*  # additional times separated by ';'
''', re.VERBOSE)

In [15]:
# Ihre Lösung :: Für Expertenniveau

def extract_openingHours(text, openingH):
    if not isinstance(text, str):  
        text = ""

    # Remove tags like 'Öffnungszeiten'
    clean_text = OPENING_TAGS.sub('', text).strip()

    # Find time blocks
    opening_matches = OPENING_PATTERN.findall(clean_text)
    if opening_matches:
    
        opening_text = ' '.join(opening_matches).strip()

        # Save description
        description_text = OPENING_PATTERN.sub('', clean_text).strip()
        
        description_text = re.sub(r'^[\W_]+$', '', description_text.strip())
        return description_text, opening_text
    else:
        return text, openingH

df_refill[['description', 'openinghours']] = df_refill.apply(
    lambda row: pd.Series(extract_openingHours(row.description, row.openinghours)),
    axis=1)

&#x1F6A9; _Checkpoint 2_: Um die Änderungen zu testen, führen Sie die folgende Zelle aus. Sie werden feststellen, dass die Spalte `description` nun weniger Werte enthält als vor Beginn dieser Aufgabe. Diese Werte sollten sich jetzt in der entsprechenden Spalte `openinghours` befinden.

In [16]:
df_refill[['description', 'openinghours']].tail(5)

,description,openinghours
id,,
3857465138ca4751b5c3bf0f37c5a7a9,Wir sind barrierefrei,Mo-Fr 10:00-19:00 Sa 10:00-16:00
157f5fd9abeb4b0da08f479dc23eb7d2,,Mo-Do 07:30-21:00 Fr;Sa 07:30-22:00 So 09:00-2...
f51f03bf784348039424566b153e897a,,Mo-Sa 08:30-20:15
f0f71f729f6940caa48afcfbf7ae8e44,,Mo-Sa 9:30-20:00
83461e1e0e3145e89ab4e612829956c3,Caffee-Haus Kette die in der EU keine Steuern ...,NaN

## Still Open
Überprüfen Sie, ob trotz der neu hinzugefügten Elemente noch leere Werte in der Spalte vorhanden sind, falls ja, wählen Sie eine geeignete Imputationsstrategie.

In [17]:
# Platz für Tests und Analysen
df_refill.openinghours.info()

<class 'pandas.core.series.Series'>
Index: 181 entries, f6b479c4210c45c1b0282138ebde8f2f to 83461e1e0e3145e89ab4e612829956c3
Series name: openinghours
Non-Null Count  Dtype
--------------  -----
144 non-null    object
dtypes: object(1)
memory usage: 6.9+ KB

Ausgewählte Imputationsstrategie: Neue Kategorie "Unbekannt"
Begründung: Etwa 80 % der Werte sind vorhanden, daher ist es nicht sinnvoll, die Spalte zu löschen. Alternativ könnte man in Betracht ziehen, die entsprechenden Zeilen zu entfernen; da dies jedoch zum Verlust wichtiger Informationen führen würde, wurde hier stattdessen die Einführung einer neuen Kategorie "Unbekannt" gewählt.

In [18]:
# Ihre Lösung
df_refill.fillna( { 'openinghours' : "Unbekannt"}, inplace = True )

&#x1F6A9; _Checkpoint 3_: Dieser Kontrollpunkt dient dazu, verschiedene Änderungen zu überprüfen, wie zum Beispiel die Spaltennamen, die Datentypen oder die Anzahl der Werte in jeder Spalte. Um die Überprüfung durchzuführen, führen Sie die folgende Zelle aus:

In [19]:
df_refill.info()

<class 'pandas.core.frame.DataFrame'>
Index: 181 entries, f6b479c4210c45c1b0282138ebde8f2f to 83461e1e0e3145e89ab4e612829956c3
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   FID           181 non-null    object
 1   geom          181 non-null    object
 2   stationsname  181 non-null    object
 3   description   181 non-null    object
 4   city          181 non-null    object
 5   address       181 non-null    object
 6   postalcode    181 non-null    object
 7   openinghours  181 non-null    object
 8   license       181 non-null    object
dtypes: object(9)
memory usage: 18.2+ KB

Wenn, Sie alle Aufgaben korrekt ausgeführt haben, ist die Vorverarbeitung nun abgeschlossen:

- Alle Spalten liegen im korrekten Datenformat vor
- Die kategorischen Spalten wurden vereinheitlicht 
- Es gibt keine fehlenden Werte 
- Es gibt keine Duplikate 
- Die Plausibilitätschecks wurden bestanden

Data Wrangling ist ein zyklischer Prozess und verläuft selten als lineare Abfolge von Einzelschritten. Eine genauere Analyse der Spalte `opening_hours` zeigt, dass noch Anpassungen notwendig sind, um z.B. saisonale Öffnungszeiten angemessen zu berücksichtigen.

Speichern Sie den von Ihnen transformierten Datensatz unter dem Namen `refill_cleaned.csv` ab.

In [21]:
# Ihre Lösung
df_refill.to_csv("KE3/refill_cleaned.csv")

___
# Data Augmentation II

Wie bereits in KE2 (Übung 3, Data Augmentation) gesehen, enthält der vorherige Datensatz nur die Zapfstellen. Um die fehlenden Informationen zu ergänzen, wird der Datensatz Mundraub verwendet, um die Informationen über Lebensmittel zu ergänzen. Der Datensatz ist in Moodle verfügbar (`mundraub.csv`).

Nachdem Sie die Auswirkungen der Verwendung des Arguments `index_col` bedacht haben, laden Sie den Datensatz unter Verwendung der Spalte, die Ihnen am geeignetsten erscheint und begründen Sie Ihre Entscheidung. Der Dataframe wird wie folgt benannt: `df_mundraub`.

In [23]:
# Ihre Lösung
df_mundraub = pd.read_csv("KE2/mundraub.csv", index_col = 0)

Begründung: index_col = 0: ist eindeutig und gibt den Datensatz, zu dem es gehört, auf einfache Art und Weise an.

Die Spalten mit den meisten fehlenden Werten im Mundraub-Datensatz sind `street`, `plz` und `city`.

## Paket unzustellbar II :: Zusatzaufgabe
Bestimmen Sie die fehlenden Werte. Diese Informationen können mit Hilfe der vorhandenen geographischen Punkte extrahiert werden, siehe Spalte `geom`.

*Hinweis: Dies ist eine freiwillige Aufgabe. Falls Sie diese bearbeiten möchten, nutzen Sie den Schieberegler unten für weitere Hinweise*

<a href="https://geopy.readthedocs.io/en/stable/">GeoPy</a> ist eine Python-Bibliothek zur Lokalisierung von Adressen, Städten, Ländern und Landmarken auf der ganzen Welt basierend auf Geokodern von Drittanbietern und anderen Datenquellen. Zu den Geokodierern gehören OpenStreetMap Nominatim, Google Geocoding API (V3) und andere. 

Bitte beachten Sie, dass das GeoPy-Modul über das Internet auf Dritte angewiesen ist. Die Beschaffung der fehlenden Daten kann daher einige Zeit in Anspruch nehmen. Außerdem kann es je nach Internetverbindung dazu kommen, dass einzelne Datenpunkte nicht abgefragt werden können, entsprechende Fehlermeldungen können Sie ignorieren. Um das Modul zu installieren, führen Sie bitte die folgende Zelle aus:

In [24]:
! pip install geopy

Defaulting to user installation because normal site-packages is not writeable
Collecting geopy
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.1-py3-none-any.whl.metadata (1.6 kB)
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
Downloading geographiclib-2.1-py3-none-any.whl (40 kB)
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.1 geopy-2.4.1

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: python3.13 -m pip install --upgrade pip

In [25]:
# Ihre Lösung
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut

# Geokodierungsdienst einrichten
geolocator = Nominatim(user_agent="mundraub")

def getAddressPlzCity(geoLoc):
    """
    Extract the city, postal code, and street from a geographical location.
    Implements caching to avoid repeated geocoding requests.
    """
    try:
        # POINT (8.263338 48.993153) -> get longitude and latitude
        longitude, latitude = geoLoc[7:-1].split(" ")
        location = geolocator.reverse((latitude, longitude), 
                                      exactly_one=True)
        val = location.raw.get('address', {})
        
        city = val.get('city') or val.get('town') or val.get('municipality') or val.get('village')
        postal_code = val.get('postcode')
        street = val.get('road')
        
        if postal_code is not None:
            postal_code = float(postal_code)
        
        return city, postal_code, street
    
    except GeocoderTimedOut:
        # Handle geocoding timeouts by returning None values
        return None, None, None
    except Exception as e:
        # Handle any other exceptions and return None values
        print(f"Error processing {geoLoc}: {e}")
        return None, None, None
    
def setMissingValuesInDS(dSet):
    """
    set missing values in the given dataset
    """
    for index, row in dSet.iterrows():
        # row with missing value?
        need_geocode = pd.isna(row['city']) or pd.isna(row['plz']) or pd.isna(row['street'])
        
        if need_geocode:
            nCi, nPl, nSt = getAddressPlzCity(row.geom)
            
        if pd.isna(row['city']):
            df_mundraub.at[index, 'city'] = nCi
        if pd.isna(row['plz']):
            df_mundraub.at[index, 'plz'] = nPl
        if pd.isna(row['street']):
            df_mundraub.at[index, 'street'] = nSt
            
# missing: Zip-code(476) City(473) Street(896)
setMissingValuesInDS(df_mundraub)

Error processing POINT (8.147097565234 49.132671149263): HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?lat=49.132671149263&lon=8.147097565234&format=json&addressdetails=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

KeyboardInterrupt:

## Luftpost
Nachdem die Werte in der Spalte `plz` gefunden wurden, muss der Datentyp so geändert werden, dass er mit dem Datentyp des vorhergehenden Datensatzes übereinstimmt. Bitte beachten Sie, dass leere Werte vorhanden sein können, falls die vorherige Zusatzaufgabe, _3.1  Paket unzustellbar II_, nicht bearbeitet wurde. In diesem Fall muss die Imputation mit "Unbekannt" erfolgen.

In [26]:
# Platz für Tests und Analysen
df_mundraub.plz.info()

<class 'pandas.core.series.Series'>
Index: 1365 entries, MRN_mundraub_4326_Point.1 to MRN_mundraub_4326_Point.1365
Series name: plz
Non-Null Count  Dtype
--------------  -----
1047 non-null   float64
dtypes: float64(1)
memory usage: 53.6+ KB

In [27]:
# Ihre Lösung
df_mundraub.plz = df_mundraub.plz.apply(lambda x: f"{int(x):05d}" if pd.notnull(x) else "Unbekannt")

&#x1F6A9; _Checkpoint 4_: Um die Änderungen zu überprüfen, führen Sie die folgende Zelle aus. Sie werden feststellen, dass keine ungültigen Werte vorhanden sind.

In [28]:
df_mundraub.plz.unique()

array(['76776', '76767', '76744', '76751', '67435', '76777', '76774',
       '76764', '76863', '76872', 'Unbekannt', '76773', '76761', '76771',
       '76879', '76829', '76726', '74889', '76877', '76833', '67360',
       '69242', '68789', '69231', '67482', '67354', '67483', '67365',
       '74924', '68799', '68804', '74915', '69168', '69190', '68809',
       '67487', '67489', '67346', '68766', '67373', '69207', '74933',
       '69226', '74925', '74821', '74858', '69181', '69245', '68775',
       '67433', '69126', '68723', '67454', '74847', '67105', '69124',
       '67459', '67166', '67165', '69117', '74867', '69214', '68782',
       '69115', '74869', '69123', '69118', '69151', '69251', '69436',
       '69439', '67146', '69120', '67122', '67125', '69121', '67141',
       '67112', '69434', '69221', '67067', '68535', '67136', '68199',
       '67098', '67159', '67065', '69412', '67061', '68239', '68526',
       '68163', '69198', '68165', '67169', '67133', '68259', '68549',
       '68159', '67167', '67071', '68167', '67063', '69493', '69469',
       '68309', '68169', '67273', '67069', '67245', '68542', '67227',
       '68305', '68519', '67229', '68307', '67271', '69488', '67259',
       '67246', '67240', '68623', '69509', '67280', '69502', '69483',
       '67547', '67551', '69514', '68642', '67549', '64668', '64646',
       '64658', '67550', '67574', '64625', '68647', '64678', '64683',
       '64686', '64673', '64665'], dtype=object)

## Back to the created_at

Überprüfen Sie den Inhalt der Spalte `created_at` und vergewissern Sie sich, dass die Elemente die gleiche Formatierung haben und dass der Datentyp korrekt ist.

In [29]:
# Platz für Tests und Analysen
df_mundraub.created_at.head(4)

FID
MRN_mundraub_4326_Point.1    Mo. 20.02.2017 - 13:15Neuburg am Rhein
MRN_mundraub_4326_Point.2           Di. 18.09.2018 - 14:23Hagenbach
MRN_mundraub_4326_Point.3               So. 28.07.2019 - 12:3076744
MRN_mundraub_4326_Point.4                    Di. 24.07.2012 - 01:15
Name: created_at, dtype: object

In [30]:
# Ihre Lösung
from datetime import datetime

# Extracts the date and time components from a given string.
def extract_datetime(date_str):
    # Find the position of the first '-' character
    pos = date_str.find('-')
    
    date_part = date_str[4:pos-1]  # Extract date 'dd.mm.yyyy'
    time_part = date_str[pos+2:pos+7]  # Extract time 'HH:MM'
    
    return f'{date_part} {time_part}'

# Clean 'created_at' column
df_mundraub['created_at'] = df_mundraub['created_at'].map(extract_datetime)

# Set the right datatype
df_mundraub['created_at'] = pd.to_datetime(df_mundraub['created_at'], 
                                           format="%d.%m.%Y %H:%M")

&#x1F6A9; _Checkpoint 5_: Um die Änderungen zu überprüfen, führen Sie die folgende Zelle aus. Das Format sollte eindeutig und einheitlich sein. Außerdem muss der Datentyp passend sein.

In [31]:
df_mundraub.created_at.head(4)

FID
MRN_mundraub_4326_Point.1   2017-02-20 13:15:00
MRN_mundraub_4326_Point.2   2018-09-18 14:23:00
MRN_mundraub_4326_Point.3   2019-07-28 12:30:00
MRN_mundraub_4326_Point.4   2012-07-24 01:15:00
Name: created_at, dtype: datetime64[ns]

## Describing the way for a Strategy
In den Spalten `description` und `street` fehlen jeweils ca. 20 Werte. Wählen Sie eine geeignete Imputationsstrategie.

In [32]:
# Platz für Tests und Analysen
indicesDes = df_mundraub[ df_mundraub.description.isnull() ].index
print(len(indicesDes))

23

Ausgewählte Imputationsstrategie: Zeilen mit "Unbekannt" ersetzen
Begründung: Da nur wenige Zeilen fehlen wird sich hier - analog zu den vorherigen Aufgaben - für die Angabe von "Unbekannt" entschieden

In [33]:
# Ihre Lösung
df_mundraub.fillna( { 'description' : "Unbekannt"}, inplace = True )

df_mundraub.fillna( { 'street' : "Unbekannt"}, inplace = True )

&#x1F6A9; _Checkpoint 6_: Verwenden Sie diesen Kontrollpunkt, um die Änderungen wie in Checkpoint 3 zu überprüfen. Bitte beachten Sie, dass leere Werte vorhanden sein können, falls die Aufgabe _3.1 Paket unzustellbar II_ nicht bearbeitet wurde

In [34]:
df_mundraub.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1365 entries, MRN_mundraub_4326_Point.1 to MRN_mundraub_4326_Point.1365
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   geom         1365 non-null   object
 1   nid          1365 non-null   int64
 2   kind         1365 non-null   object
 3   street       1365 non-null   object
 4   plz          1365 non-null   object
 5   city         1050 non-null   object
 6   description  1365 non-null   object
 7   created_at   1365 non-null   datetime64[ns]
 8   url          1365 non-null   object
dtypes: datetime64[ns](1), int64(1), object(7)
memory usage: 138.9+ KB

Speichern Sie den von Ihnen transformierten Datensatz unter dem Namen `mundraub_cleaned.csv` ab.

In [35]:
# Ihre Lösung
df_mundraub.to_csv("KE3/mundraub_cleaned.csv")

# Notizen
Persönliche Notizen ;)