Name:
Matrikelnummer:

___

In [1]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt

___
**_Bitte beachten:_**

- In Code-Zellen soll (bei Bedarf kommentierter) Code eingefügt werden. In Raw-Zellen erwarten wir Antworten im Freitext-Format.
- Fragestellungen sind teilweise bewusst etwas offener formuliert, weil Sie auch im Arbeitsleben nur selten mit ganz spezifischen Anweisungen rechnen können.Es gibt häufig mehrere mögliche Lösungen, dies wird in der Korrektur  berücksichtigt.

___

# (I can't get no) satisfaction
Wir arbeiten weiterhin mit dem Datensatz über die Zufriedenheit von Angestellten einer fiktiven Firma. In dieser Kurseinheit werden wir einige Techniken zur Datenvisualisierung anwenden.

*Hinweise:*
- *Für die Visualisierungsaufgaben gibt es meist unterschiedliche Lösungswege. Wir verwenden in den meisten Fällen die Bibliothek `matplotlib`. Sie können die Aufgaben auch mit anderen Bibliotheken, wie z.B. `seaborn`, lösen. Denken Sie in dem Fall daran, die entsprechende Bibliothek zu installieren und zu importieren.*
- *Denken Sie bei der Erstellung der Plots an Titel und Achsenbeschriftung!*

**Daten laden**

Wir verwenden nun den transformierten Datensatz aus KE3. Sollten Sie die Aufgaben aus KE3 erfolgreich absolviert haben, können Sie Ihren Datensatz verwenden, ansonsten finden Sie die entsprechende csv-Datei (`employees_satisfaction_transformed.csv`) im Moodle.

In [11]:
# Datensatz laden
# Laden Sie den Datensatz wieder so, dass die erste Spalte als Index (Row Label) verwendet wird
# Wir verwenden hier den transformierten Datensatz aus KE3
df = pd.read_csv("../data/employees_satisfaction_transformed_orig.csv", index_col=0)

Für Datumsberechnungen wandeln wir wieder den Datentyp von `entry_date` um.

In [12]:
df["entry_date"] = pd.to_datetime(df["entry_date"], format="%Y-%m-%d")

In [13]:
df

,age,department,education,recruitment_type,job_level,rating,awards,certifications,salary,gender,entry_date,satisfied
0,28,HR,Postgraduate,Referral,5,2.0,1,0,78075.0,Male,2019-02-01,1
1,50,Technology,Postgraduate,Recruitment Agency,3,5.0,2,1,38177.1,Male,2017-01-17,0
2,43,Technology,Undergraduate,Referral,4,1.0,2,0,59143.5,Female,2012-08-27,1
3,44,Sales,Postgraduate,On-Campus,2,3.0,0,0,26824.5,Female,2017-07-25,1
4,33,HR,Undergraduate,Recruitment Agency,2,1.0,5,0,26824.5,Male,2019-05-17,1
...,...,...,...,...,...,...,...,...,...,...,...,...
495,49,HR,Postgraduate,On-Campus,2,5.0,6,0,26824.5,Male,2014-03-21,1
496,24,Technology,Undergraduate,Referral,2,4.0,2,0,26824.5,Female,2018-02-20,0
497,34,Marketing,Postgraduate,On-Campus,1,Unavailable,2,0,21668.4,Male,2020-10-20,1
498,26,Technology,Undergraduate,Walk-in,2,1.0,1,1,26824.5,Male,2012-05-18,0
499,26,Technology,Undergraduate,Recruitment Agency,3,4.0,3,0,38177.1,Male,2018-12-28,0

## Data Analysis

### Alter

**Wie ist das durchschnittliche Alter der Angestellten? Unterscheidet sich dieses, in Abhängigkeit von der Abteilung?**

In [14]:
# Ihre Lösung
df.groupby("department")["age"].mean()

department
HR            39.367925
Marketing     38.784946
Purchasing    40.140351
Sales         38.816092
Technology    41.051020
Name: age, dtype: float64

In [15]:
df["age"].mean()

39.670682730923694

Ihre Antwort:

**In welcher Abteilung arbeitet der älteste Mann, in welcher die jüngste Frau?**

In [ ]:
# Ihre Lösung

In [18]:
# Abteilung ältester Mann
df[df["gender"] == "Male"].groupby("department").max("age")

            age  job_level  awards  certifications   salary  satisfied
department
HR           54          5       9               1  78075.0          1
Marketing    54          5       9               1  78075.0          1
Purchasing   54          5       9               1  78075.0          1
Sales        54          5       9               1  78075.0          1
Technology   56          5       9               1  78075.0          1

In [19]:
# Abteilung jüngste Frau
df[df["gender"] == "Female"].groupby("department").min("age")

            age  job_level  awards  certifications   salary  satisfied
department
HR           22          1       0               0  21668.4          0
Marketing    24          1       0               0  21668.4          0
Purchasing   24          1       0               0  21668.4          0
Sales        25          1       0               0  21668.4          0
Technology   23          1       0               0  21668.4          0

Ihre Antwort:

### Awards

**Wie ist die durchschnittliche Anzahl Awards? Wie ist der Median? Welcher Wert ist aussagekräftiger?**

In [ ]:
# Ihre Lösung

In [20]:
# Mean
df["awards"].mean()

4.586345381526105

In [22]:
# Median
df["awards"].median()

5.0

Ihre Antwort:

### Zufriedenheit

**In welcher Abteilung sind die meisten zufriedenen Angestellten?**

In [23]:
# Ihre Lösung
df.groupby("department")["satisfied"].sum()

department
HR            73
Marketing     60
Purchasing    80
Sales         70
Technology    73
Name: satisfied, dtype: int64

Ihre Antwort:

**Und in welcher Abteilung sind die Angestellten im Schnitt am zufriedensten?**

In [24]:
# Ihre Lösung
df.groupby("department")["satisfied"].mean()

department
HR            0.688679
Marketing     0.645161
Purchasing    0.701754
Sales         0.804598
Technology    0.744898
Name: satisfied, dtype: float64

Ihre Antwort:

### Fairness

**Gender Pay Gap**

Bekommen Männer und Frauen der fiktiven Firma das gleiche Gehalt?

In [26]:
# Ihre Analysen
df.groupby("gender")["salary"].mean()

gender
Female     43627.387500
Male       47042.079468
Unknown    46651.800000
Name: salary, dtype: float64

Ihre Einschätzung:

Betrachten Sie den Datensatz weiterhin mit Fokus auf dem Thema *Fairness*. Was fällt Ihnen auf? Welche Aspekte könnte man noch untersuchen?

Ihre Antwort:

In [ ]:
# Ihre Analysen

Ihre Einschätzung in Bezug auf Fairness:

## Data Visualization

### Säulendiagramm

Zur Erinnerung (siehe Buch S.335): Es gelten folgende Aspekte bei Säulendiagrammen:

> **Regel**: Die Säulen müssen bei 0 anfangen!

> **Richtlinie**: Vertikale Balken eignen sich gut für dichtere Daten mit weniger Schwankungen.

> **Richtlinie**: Horizontale Balken sind besser für mehr Variation und/oder längere Labels.

Beschreiben Sie für die folgenden Aufgabenstellungen neben Ihrer Interpretation des Diagramme auch, ob Säulendiagramme für die Fragestellung geeignet sind und wenn nicht, welche Regel/Richtlinien verletzt sind.

**In welchem Department arbeiten die meisten Personen?**

Erstellen Sie zur Beantwortung der Frage ein Säulendiagramm, das die Anzahl Angestellte pro Department darstellt.

In [ ]:
# Ihre Lösung

Ihre Interpretation des Diagramms:

**Unterscheidet sich die durchschnittliche Anzahl Awards, in Abhängigkeit von der Ausbildung, stark?**

Erstellen Sie hierfür wiederum ein Säulendiagramm.

In [ ]:
# Ihre Lösung

Ihre Interpretation des Diagramms:

**Sind Angestellte mit einem höheren Gehalt im Schnitt zufriedener?**

Erstellen Sie hierzu ein Liniendiagramm, das pro Gehaltsklasse die durchschnittliche Zufriedenheit angibt.

In [ ]:
# Ihre Lösung

Ihre Interpretation des Diagramms:

### Liniendiagramm

Zur Erinnerung (siehe Buch S.339): Es gelten folgende Aspekte bei Liniendiagrammen:

> **Regel**: Die Datenpunkte müssen Werte im *Zeitverlauf* darstellen.

> **Richtlinie**: Die Datenpunkte sollten etwa 2/3 des vertikalen Diagrammbereichs einnehmen.

> **Richtlinie**: Vier oder weniger Zeilen sollten deutlich gefärbt/beschriftet sein.

Beschreiben Sie für die folgenden Aufgabenstellungen neben Ihrer Interpretation des Diagramme auch, ob Liniendiagramme für die Fragestellung geeignet sind und wenn nicht, welche Regel/Richtlinien verletzt sind.

**Steigt das durchschnittliche Alter pro Job-Level, fällt es oder bleibt es ungefähr gleich?**

Beantworten Sie diese Frage mithilfe eines Liniendiagramms.

In [ ]:
# Ihre Lösung

Ihre Interpretation des Diagramms:

**Verändert sich das Recruiting über die Jahre?**

Erstellen Sie hierzu ein Liniendiagramm, das die Anzahl der Neuanstellungen über die Zeit (`entry_date`) in Abhängigkeit vom Recruitment-Typ darstellt.

In [ ]:
# Ihre Lösung

Ihre Interpretation des Diagramms:

**Sind Angestellte, die schon länger in der Firma sind, im Schnitt zufriedener?**

Beantworten Sie diese Frage ebenfalls mithilfe eines Liniendiagramms. Gruppieren Sie die Angestellten dafür nach dem Einstellungsjahr (`df["entry_date"].dt.year`).

In [ ]:
# Ihre Lösung

Ihre Interpretation des Diagramms:

### Kreisdiagramm

Zur Erinnerung (siehe Buch S.330): Es gelten folgende Aspekte bei Liniendiagrammen:

> **Regel**: Die Datenkategorien müssen konzeptionell ein einziges "Ganzes" ergeben.

> **Richtlinie**: Die Anzahl der Kategorien sollte auf fünf oder weniger reduziert werden.

> **Richtlinie**: Der Anteil der hervorzuhebenden Daten sollte 1/4, 1/3, 1/2, 2/3 oder 3/4 der Gesamtmenge betragen.

Beschreiben Sie für die folgenden Aufgabenstellungen neben Ihrer Interpretation des Diagramme auch, ob Kreisdiagramme für die Fragestellung geeignet sind und wenn nicht, welche Regel/Richtlinien verletzt sind.

**Gibt es Abteilungen, in denen mehr Frauen als Männer arbeiten?**

Beantworten Sie diese Frage mithilfe von Kreisdiagrammen (ein Kreisdiagramm pro Abteilung).

In [ ]:
# Ihre Lösung

Ihre Interpretation des Diagramms:

**In Abhängigkeit vom Education-Typ: Welche Angestellten haben mehr Awards?**

Beantworten Sie diese Frage mithilfe von Kreisdiagrammen (ein Kreisdiagramm pro Education-Typ).

In [ ]:
# Ihre Lösung

Ihre Interpretation des Diagramms: